name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    uses: afv22-projects/.github/.github/workflows/release-please.yml@main
    secrets: inherit

  publish:
    needs: release-please
    if: needs.release-please.outputs.release-created == 'true'
    uses: afv22-projects/.github/.github/workflows/publish-firefox-addon.yml@main
    with:
      tag-name: ${{ needs.release-please.outputs.tag-name }}
      release-note: ${{ needs.release-please.outputs.body }}
    secrets:
      amo-api-key: ${{ vars.AMO_API_KEY }}
      amo-api-secret: ${{ secrets.AMO_API_SECRET }}
